steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - gcloud
  - composer
  - environments
  - storage
  - dags
  - import
  - --environment
  - alevz-composer
  - --location
  - us-central1
  - --source
  - sample.py
