steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud','composer','environments','storage','dags','import','--environment','${_COMPOSER}','--location','${_LOCATION}','--source','${_SOURCE}']
